version: '3.1'

services:
  backend:
    image: coding_challenge_be:latest
    build:
      context: coding_challenge_kindalab_sfmovies_backend
      dockerfile: backend.Dockerfile
    networks:
      - cc_net
    ports:
      - 8000:8000
  frontend:
    image: coding_challenge_fe:latest
    build:
      context: coding_challenge_kindalab_sfmovies_frontend
      dockerfile: frontend.Dockerfile
    networks:
      - cc_net
    ports:
      - 5001:3000
    depends_on:
      - backend

networks:
  cc_net: